var message = "Error!Please enter a valid password.";
alert(message);
var message = "Welcome To Js Land...\nHappy coding!";
alert(message);
message = "Welcome to Js Land";
alert(message);
message = "Happy Coding!\nPrevent this page from creating additional dialogs.";
alert(message);
console.log("hello...I can run JS through my web browser's console");
alert("hello...I can run JS through my web browser's console");
message = "Hello World!"
alert(message);
var userName ="Ahmed";
alert(userName);
var myName = "Ahmed Rauf";
alert(myName);
var age = "18 years old";
alert( "I am " + age);
message = "Certified Mobile Application Development";
alert(message);
var pizza = "PIZZA\nPIZZ\nPIZ\nPI\nP";
alert(pizza);
var email = "My email address is example@example.com";
alert(email);
var book = "'I am trying to learn JavaScript from the Book 'A smarter way to learn JavaScript'.";
alert(book  );
var sign = " ▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬ ";
alert(sign);
var track= "You  have visited this site 50 times";
alert (track);